language: php

services:
  - mongodb
  - memcache
  - couchdb
  - redis

env:
  # Run one build with as many enabled and compatible extensions as possible.
  - PHP_EXT="memcached redis"
  # Test compatiblity with opcode caches in isolation.
  - PHP_EXT=apc
  - PHP_EXT=xcache
  - PHP_EXT=opcache
  # Test each database in isolation.
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  - DB=mongodb PHP_EXT=mongo
  - DB=couchdb

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  exclude:
    - php: 5.5
      env: PHP_EXT=apc
    - php: 5.6
      env: PHP_EXT=apc
    - php: 5.6
      env: PHP_EXT=xcache

before_script:
  - php tests/ci/depends.php
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database lithium_test; create database lithium_test_alternative;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database lithium_test;' -U postgres; psql -c 'create database lithium_test_alternative;' -U postgres; fi"
  - cd ..
  - mkdir libraries
  - mv lithium libraries
  - git clone --branch=master --depth=1 --quiet git://github.com/UnionOfRAD/li3_fixtures.git libraries/li3_fixtures
  - mkdir -p ci/config
  - cd ci
  - cp ../libraries/lithium/tests/ci/config/libraries.php config/libraries.php
  - cp ../libraries/lithium/tests/ci/config/bootstrap.php config/bootstrap.php
  - php -i

script:
  # Run all tests.
  - sh -c "if [ '$DB' = '' ]; then ../libraries/lithium/console/li3 test --filters=Profiler ../libraries/lithium/tests/cases; fi"
  - sh -c "if [ '$DB' = '' ]; then ../libraries/lithium/console/li3 test --filters=Profiler ../libraries/lithium/tests/integration; fi"
  # Run just the database related tests.
  - sh -c "if [ '$DB' != '' ]; then ../libraries/lithium/console/li3 test --filters=Profiler ../libraries/lithium/tests/cases/data; fi"
  - sh -c "if [ '$DB' != '' ]; then ../libraries/lithium/console/li3 test --filters=Profiler ../libraries/lithium/tests/integration/data; fi"

notifications:
  email: false
