language: php

services:
  - mongodb
  - memcache
  - couchdb

env:
  # Run one build with as many enabled and compatible extensions as possible.
  # - PHP_EXT=""
  # Test compatiblity with opcode caches in isolation.
  - PHP_EXT=apc
  - PHP_EXT=xcache
  # Test each database in isolation.
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  - DB=mongodb PHP_EXT=mongo
  - DB=couchdb

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - php tests/ci/depends.php
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database lithium_test; create database lithium_test_alternative;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database lithium_test;' -U postgres; psql -c 'create database lithium_test_alternative;' -U postgres; fi"
  - cd ..
  - mkdir libraries
  - mv lithium libraries
  - git clone --branch=master --depth=1 --quiet git://github.com/UnionOfRAD/li3_fixtures.git libraries/li3_fixtures
  - mkdir -p ci/config
  - cd ci
  - cp ../libraries/lithium/tests/ci/config/libraries.php config/libraries.php
  - cp ../libraries/lithium/tests/ci/config/bootstrap.php config/bootstrap.php

script:
  - ../libraries/lithium/console/li3 test --filters=Profiler ../libraries/lithium/tests/cases
  - ../libraries/lithium/console/li3 test --filters=Profiler ../libraries/lithium/tests/integration

notifications:
  email: false
